### PR TITLE
Tolerate invalid parents when computing mutation parents

### LINKED ISSUE #3303: `compute_mutation_parents` errors when existing mutation parents don't make sense
Here's a MWE:
```
t = tskit.TableCollection(sequence_length=1.0)

t.nodes.add_row(time=0)
t.sites.add_row(position=0.0, ancestral_state='A')
t.mutations.add_row(node=0,site=0, derived_state='C', parent=0)

t.compute_mutation_parents()
```
This errors with
```
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/pyslim/test.py", line 9, in <module>
    t.compute_mutation_parents()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/peter/projects/tskit-dev/tsvenv/lib/python3.13/site-packages/tskit/tables.py", line 3864, in compute_mutation_parents
    self._ll_tables.compute_mutation_parents()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
_tskit.LibraryError: Parent mutation refers to itself. (TSK_ERR_MUTATION_PARENT_EQUAL)
```

Similar errors occur if the `parent` points at a mutation at a different site, etcetera. This is new behavior - previously, things like [this unit test](https://github.com/tskit-dev/pyslim/blob/main/tests/test_tree_sequence.py#L925) ran fine; now they error. (That test goes through and throws out every other mutation, so the resulting `parent` references no longer make sense.)

Since `compute_mutation_parents` does not need to look at the `parents` array, I don't think it makes sense to check integrity of what's there already? Huh, I would have *thought* the solution would be just not adding `TSK_CHECK_MUTATION_PARENTS` to [this line](https://github.com/tskit-dev/tskit/pull/3212/files#diff-a7113e19292b94afe45f78ce230588105799e862a5f6f15d1af1ba81816f6e76R12442), but it is in fact not there, so I'm not sure why this is being checked?

Huh: I see in the docstring for `compute_mutation_parents` that
> This will produce an error if mutations         are not sorted (i.e., if a mutation appears before its mutation parent)        *unless* the two mutations occur on the same branch, and have unknown times        in which case there is no way to detect the error.

Perhaps the problem is something to do with #3257. I will look into it more.

*Side note:* I see in [that PR](https://github.com/tskit-dev/tskit/pull/3212#issuecomment-2970316995) the good note that error messages should explain how to load the tables and correct the issue, but that isn't done in that PR (maybe it's been done since?).

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #3303

### CODE REVIEW

File: c/tskit/tables.c [hunk 1]
```diff
@@ -12436,22 +12436,48 @@ tsk_table_collection_compute_mutation_parents(
...
         }
     }
 
     ret = tsk_table_collection_compute_mutation_parents_to_array(
         self, self->mutations.parent);
     if (ret != 0) {
-        goto out;
+        goto restore;
+    }
+
```
Comment (jeromekelleher) [inline c/tskit/tables.c:12472]: I think it's simpler if we just have one exit point and ``goto out`` on error. We've safely gated anyway with the ``restore_parents`` flag, so I think its clear.

File: c/tests/test_tables.c [hunk 2]
```diff
@@ -10775,6 +10775,41 @@ test_check_integrity_bad_mutation_parent_topology(void)
...
+    site = tsk_site_table_add_row(&tables.sites, 0.0, "A", 1, NULL, 0);
+    CU_ASSERT_FATAL(site >= 0);
+    ret = tsk_mutation_table_add_row(
+        &tables.mutations, site, 1, TSK_NULL, TSK_UNKNOWN_TIME, "C", 1, NULL, 0);
+    CU_ASSERT_EQUAL_FATAL(ret, 0);
+
+    ret = tsk_table_collection_build_index(&tables, 0);
+    CU_ASSERT_EQUAL_FATAL(ret, 0);
+    tables.mutations.parent[0] = 42;
+
```
Comment (jeromekelleher) [inline c/tests/test_tables.c:10806]: Need to check the restore behaviour on error also

File: python/tests/test_tables.py [hunk 3]
```diff
@@ -3540,6 +3540,18 @@ def test_table_references(self):
...
+        parent = tables.nodes.add_row(time=1.0)
+        child = tables.nodes.add_row(time=0, flags=tskit.NODE_IS_SAMPLE)
+        tables.edges.add_row(left=0.0, right=1.0, parent=parent, child=child)
+        site = tables.sites.add_row(position=0.0, ancestral_state="A")
+        tables.mutations.add_row(site=site, node=child, derived_state="C")
+        tables.build_index()
+        tables.mutations.parent[:] = 42
+        tables.compute_mutation_parents()
+        assert tables.mutations.parent[0] == tskit.NULL
+
```
Comment (jeromekelleher) [inline python/tests/test_tables.py:3554]: Another test checking the parent data is preserved on error

File: c/tskit/tables.c (hunk 1 above)
Comment (petrelharp) [reply c/tskit/tables.c:12472]: agree - currently it reads as if an error in `compute_mutation_parents_to_array` might try to restore even if there's no backup (because of `TSK_NO_CHECK_INTEGRITY`). it won't because of the flag, but still.

File: python/tests/test_tables.py (hunk 3 above)
Comment (petrelharp) [reply python/tests/test_tables.py:3554]: if possible we should check the data is preserved on error even if `TSK_NO_CHECK_INTEGRITY` is on

File: c/tests/test_tables.c (hunk 2 above)
Comment (benjeffery) [reply c/tests/test_tables.c:10806]: https://github.com/tskit-dev/tskit/pull/3309/commits/193af2205c1252fcd41e1b02627b475787c674ea

File: c/tskit/tables.c (hunk 1 above)
Comment (benjeffery) [reply c/tskit/tables.c:12472]: https://github.com/tskit-dev/tskit/pull/3309/commits/f3836169292797e32053adaf0f81b33d56905610

File: python/tests/test_tables.py (hunk 3 above)
Comment (benjeffery) [reply python/tests/test_tables.py:3554]: https://github.com/tskit-dev/tskit/pull/3309/commits/a3e12f791a705030556d94a23fe0cb3147617c46
