### PR TITLE
Tidy up genetic_relatedness

### LINKED ISSUE #973: Tidy ups for genetic_relatedness
From @petrelharp's comments [here](https://github.com/tskit-dev/tskit/pull/898#issuecomment-721528139) in #898:

- I think the denominator should always be 2, and should be incorporated into the summary function.
- I think the C and python methods should be consistently named: one is relatedness, the other genotype_relatedness; I think we decided to do the second thing.

~We also want to merge the current tests for genetic_relatedness into the existing framework for stats tests. Hopefully this can be done by following the pattern for something like [trait regression](https://github.com/tskit-dev/tskit/blob/main/python/tests/test_tree_stats.py#L4306)~

~I'd *imagine* that we'd basically be moving everything out of the current test_covariance.py module, but maybe not.~

[edit testing stuff moved to #974]

How does this sound @brieuclehmann?

### PR DESCRIPTION
**Pull request by brieuclehmann**
Small changes to naming of genetic_relatedness in the tests and the C implementation.

Moved the denominator 2 into the summary function.

Fixes #973

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/975/)

File: c/tests/test_stats.c [hunk 1]
```diff
@@ -1346,20 +1346,20 @@ test_paper_ex_relatedness(void)
     tsk_treeseq_from_text(&ts, 10, paper_ex_nodes, paper_ex_edges, NULL, paper_ex_sites,
         paper_ex_mutations, paper_ex_individuals, NULL, 0);
 
-    ret = tsk_treeseq_relatedness(&ts, 2, sample_set_sizes, samples, 1, set_indexes, 0,
-        NULL, &result, TSK_STAT_SITE);
+    ret = tsk_treeseq_genetic_relatedness(&ts, 2, sample_set_sizes, samples, 1,
+        set_indexes, 0, NULL, &result, TSK_STAT_SITE);
     CU_ASSERT_EQUAL_FATAL(ret, 0);
```
Comment (jeromekelleher) [inline c/tests/test_stats.c:1351]: It would be nice to check the value of ``result`` here also. Can you put in an assert ``CU_ASSERT_DOUBLE_EQUAL`` here with the required value (fine to printf this out first to get the value - we just want to catch problems early if there's ever any regressions).

**Review by jeromekelleher — APPROVED** [review]
Looks great, thanks @brieuclehmann! One tiny update to add to the C test case and good to merge then.

ps. When you're making a small change to PR like this, ``git commit -a --amend`` is quite handy. It'll just change the previous commit, saving you the trouble of running rebase and squash.

File: c/tests/test_stats.c (hunk 1 above)
Comment (brieuclehmann) [reply c/tests/test_stats.c:1351]: Yep, no problem. Should I do this as part of this PR or add as part of the tests issue?

Comment (jeromekelleher) [reply c/tests/test_stats.c:1351]: Either, it's up to you. Just let me know.

Comment (brieuclehmann) [reply c/tests/test_stats.c:1351]: I'll do it with the tests!

Comment (jeromekelleher) [reply c/tests/test_stats.c:1351]: OK, merging.

**Comment by petrelharp** [comment]
lgtm, thx!
