### PR TITLE
Complete checks for uninitialised objects in C Python module

### LINKED ISSUE #933: Add tests for uninitialised Python objects
The Python C API can current segfault in quite a few places if a user deliberately creates an instance without calling ``__init__`` using ``__new__``. While this is a remote corner case, we should tie up this loose-end and avoid the segault. The way to do it is to make sure ``ClassName_check_state`` is called before accessing any of the memory of the embedded C object.

The test for doing this on the various objects can be adopted from [test_uninitialised](https://github.com/tskit-dev/msprime/blob/main/tests/test_lowlevel.py#L930) in msprime.

### PR DESCRIPTION
**Pull request by benjeffery**
## Description

It was possible to seg fault the C Python module. This PR adds checks to all methods.

Fixes #933 

# PR Checklist:

- [X] Tests that fully cover new/changed functionality.
- [X] Documentation including tutorial content if appropriate.
- [X] Changelogs, if there are API changes.

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/981/)

File: python/_tskitmodule.c [hunk 1]
```diff
@@ -5642,7 +5765,7 @@ TreeSequence_get_node(TreeSequence *self, PyObject *args)
     Py_ssize_t record_index, num_records;
     tsk_node_t record;
 
-    if (TreeSequence_check_tree_sequence(self) != 0) {
```
Comment (jeromekelleher) [inline python/_tskitmodule.c:5645]: Yes, I was a bit worried about inconsistencies - thanks for sorting that out.

**Review by jeromekelleher — APPROVED** [review]
Looks great, thanks!
