### PR TITLE
Fix flag handling in Python C API

### LINKED ISSUE #1027: Flags are parsed as signed in the C Python extension.
`tables.nodes.flags` and `tables.individuals.flags` are listed as dtype `np.uint32`. But it looks like the C library is expecting them to be set as signed 32 bit ints instead:

```
ts = msprime.simulate(4, mutation_rate=10)
tables = ts.dump_tables()
tables.nodes.add_row(flags = np.iinfo(np.int32).max)  # works
tables.nodes.add_row(flags = np.iinfo(np.uint32).max)  # fails with "OverflowError: signed integer is greater than maximum"
tables.individuals.add_row(flags = np.iinfo(np.int32).max)  # works
tables.individuals.add_row(flags = np.iinfo(np.uint32).max)  # fails with "OverflowError: signed integer is greater than maximum"
```

### PR DESCRIPTION
**Pull request by benjeffery**
## Description

Flags were not handled right in the Python C API layer. The PR introduces a converter function to fix this.

Fixes #1027 

# PR Checklist:

- [X] Tests that fully cover new/changed functionality.
- [X] Documentation including tutorial content if appropriate.
- [x] Changelogs, if there are API changes.

### CODE REVIEW

**Comment by benjeffery** [comment]
Gah, this new code doesn't like `numpy.uint32` as a type to covert.

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/tskit-docs/PR-1031/)

**Comment by benjeffery** [comment]
Thought of a better way to do this - resetting to draft.

**Comment by benjeffery** [comment]
@jeromekelleher I've found a way which copes with `numpy.uint32`. Should be good to go.

**Comment by benjeffery** [comment]
Ha spoke too soon, it failed on windows.

File: python/_tskitmodule.c [hunk 1]
```diff
@@ -736,6 +736,31 @@ make_file(PyObject *fileobj, const char *mode)
     return ret;
 }
 
+static int
+uint32_converter(PyObject *py_obj, uint32_t *uint_out)
+{
+    int64_t temp_long;
+    int ret = 0;
+
+    if (!PyArg_Parse(py_obj, "l", &temp_long)) {
```
Comment (jeromekelleher) [inline python/_tskitmodule.c:745]: Probably best to use [this function](https://docs.python.org/3/c-api/long.html#c.PyLong_AsLongLongAndOverflow) if we want to be absolutely 100% sure.

File: python/tskit/tables.py [hunk 2]
```diff
@@ -721,6 +721,7 @@ def add_row(self, flags=0, time=0, population=-1, individual=-1, metadata=None):
         :rtype: int
         """
         metadata = self.metadata_schema.validate_and_encode_row(metadata)
+        print(flags)
```
Comment (jeromekelleher) [inline python/tskit/tables.py:724]: print

File: python/_tskitmodule.c (hunk 1 above)
Comment (jeromekelleher) [reply python/_tskitmodule.c:745]: Hmm, looks like we're already catching overflows properly anyway, so maybe no need to bother with that. We can't assume a long is 64 bit though, we need a ``long long`` for that.

**Review by jeromekelleher — COMMENTED** [review]
LGTM, minor comments.

File: python/tskit/tables.py (hunk 2 above)
Comment (benjeffery) [reply python/tskit/tables.py:724]: Yeah I'm still debugging windows.

File: python/_tskitmodule.c (hunk 1 above)
Comment (benjeffery) [reply python/_tskitmodule.c:745]: I tried `PyLong_AsLongLongAndOverflow` but it doesn't like the `np.uint32` objects that `add_row` currently recieves.

Comment (jeromekelleher) [reply python/_tskitmodule.c:745]: Dammit. PyArg_Parse is good anyway, just use a long long. That's probably the issue on windows, as a long is 32 bits there.

File: python/_tskitmodule.c [hunk 3]
```diff
@@ -736,6 +736,32 @@ make_file(PyObject *fileobj, const char *mode)
     return ret;
 }
 
+static int
+uint32_converter(PyObject *py_obj, uint32_t *uint_out)
+{
+    int64_t temp_long;
```
Comment (jeromekelleher) [inline python/_tskitmodule.c:742]: This needs to be declared a ``long long`` I think, as that's what the python C code is assuming. It could happen that the long long is more than 64 bits or something - anyway, no point in mixing fixed widths and old style types. We can be sure a long long is at least 64 bits.

**Review by jeromekelleher — APPROVED** [review]
LGTM
